# Foreword {-}

*Author: Przemyslaw Biecek ([University of Warsaw](https://www.mimuw.edu.pl/))*

## Why?

In 2020, as part of the Interpretable Machine Learning course, students created [XAI Stories](https://pbiecek.github.io/xai_stories), an ebook that collects the experiences of the subjects covered in the form of a series of chapters on different applications of XAI techniques.

This was a great idea. Each team developed an interesting solution and then described it in a clear and interesting way. Some of these results were later presented at relevant industry conferences.

This year we are continuing this experiment but focusing on applications in one sector - retail analytics. In cooperation with students from the universities of Warsaw and Lodz, as well as partners from McKinsey and Shumee, this ebook has been created - presenting various ideas and applications on how to use predictive modelling in retail, but also how to enrich these solutions with XAI.

I hope that the presented solutions will trigger development of new interesting solutions implementing explainable machine learning in the retail industry

## What?

**This ebook collects examples of the use of different methods from the XAI family for  real-world predictive problems in retail.**

In the following chapters, we show example applications of different XAI techniques to problems in retail analytics.

These examples are called *XAI stories* and like every good story, each one has a structure. It starts with a description of the predictive problem, goes on to describe the proposed model or models. The models are x-rays using XAI techniques to finish the chapter with a point.

## How?

For XAI stories to be credible they need not only a strong predictive model but also business validation of the proposed modeling and an explanation approach.

Each group of students was assigned mentors from data scientists and experts within McKinsey Digital: a consultant and a data scientist. The mentors, together with the students, searched for the strengths and weaknesses of XAI applications in specific problems. At McKinsey Digital, we help our clients create change that matters—transformation, enabled by technology and sustained through capabilities. We drive transformation and build businesses by bringing together the capabilities needed to help organizations grow and thrive in the digital age. We help our clients harness the power of data and artificial intelligence, modernize core technology and capitalize on new technology, optimize and automate operations, fuel digital growth, create stunning digital experiences, and build digital talent and culture.

## About academic partners

**The Faculty of Mathematics, Informatics, and Mechanics, University of Warsaw**

The Faculty of Mathematics, Informatics, and Mechanics Department offers a master's degree with a specialization in mathematical statistics or a specialization in machine learning. The curriculum includes many interesting subjects related to computational statistics or deep learning. 

This book was prepared as part of the Interpretable Machine Learning 2020/2021 elective course. Find more details about the [MIM classes here](https://usosweb.uw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&kod=1000-1M18WUM) and about [the faculty, here](https://www.mimuw.edu.pl/en).

**The Department of Econometrics, University of Łódź**

TODO. Prof Paweł Baranowski is the lead collaborator from UoŁ.


## About business partner

**McKinsey & Company**

TODO

